### ISSUE TITLE
Unknow error   RELOAD UI ?

### ISSUE THREAD

**Issue by yovca** [dwainscheeren/dwains-lovelace-dashboard#482]
I have a problem...
![Dwain](https://user-images.githubusercontent.com/59418628/165485268-6e0c600f-b3dc-4a10-99f3-7273c7a637b0.jpg)

**Comment by dwainscheeren** [comment]
What does your ha error log say? Do you got lovelace_gen installed or hki? Did you had dd before installed?

**Comment by yovca** [comment]
Hi, thanks for your reply...🙂
Yes, I have DD before installed...
This is my log file: 


Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/dwains_dashboard/lovelace/views/main/01.homepage.yaml:3
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 23:33:09 (2 occurrences)
Last logged: 23:33:12

[548219973744] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/lovelace/websocket.py", line 30, in send_with_error_handling
    result = await func(hass, connection, msg, config)
  File "/usr/src/homeassistant/homeassistant/components/lovelace/websocket.py", line 72, in websocket_lovelace_config
    return await config.async_load(msg["force"])
  File "/usr/src/homeassistant/homeassistant/components/lovelace/dashboard.py", line 188, in async_load
    is_updated, config = await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/lovelace/dashboard.py", line 207, in _load_config
    config = load_yaml(self.path, Secrets(Path(self.hass.config.config_dir)))
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 111, in load_yaml
    return parse_yaml(conf_file, secrets)
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 123, in parse_yaml
    yaml.load(content, Loader=lambda stream: SafeLineLoader(stream, secrets))
  File "/usr/local/lib/python3.9/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/usr/local/lib/python3.9/site-packages/yaml/constructor.py", line 51, in get_single_data
    return self.construct_document(node)
  File "/usr/local/lib/python3.9/site-packages/yaml/constructor.py", line 55, in construct_document
    data = self.construct_object(node)
  File "/usr/local/lib/python3.9/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 253, in _ordered_dict
    nodes = loader.construct_pairs(node)
  File "/usr/local/lib/python3.9/site-packages/yaml/constructor.py", line 155, in construct_pairs
    value = self.construct_object(value_node, deep=deep)
  File "/usr/local/lib/python3.9/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 244, in _include_dir_merge_list_yaml
    loaded_yaml = load_yaml(fname, loader.secrets)
  File "/config/custom_components/dwains_dashboard/process_yaml.py", line 37, in load_yamll
    stream = io.StringIO(jinja.get_template(fname).render({
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 926, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/config/custom_components/dwains_dashboard/lovelace/views/main/01.homepage.yaml", line 3, in top-level template code
    - title: {{ _dd_trans.home.title }}
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 475, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: '_dd_trans' is undefined

**Comment by JoeMajoros** [comment]
I had the same issue... The process should be:
Step 1: Remove DD from integration then from HACS
Step 2: Install DD from HACS
Step 3: IMPORTANT that you restart your HA before you actually go and add the DD integration
Step 4: once restrated add DD from Integration

**Comment by azafred** [comment]
Following as I am getting the same issue. (The process above from JoeMajoros did alas not do the trick)

**Comment by dwainscheeren** [comment]
That error is refering to file `01.homepage.yaml` with the line `- title: {{ _dd_trans.home.title }}` that code is no where used in dd 3.0 so I think you didnt follow the upgrade guide from v2 to v3. Please read all t he steps, remove 2.0 completely then reboot, then install 3.0  https://dwainscheeren.github.io/dwains-lovelace-dashboard/v3/information/migrate-v2-to-v3.html

**Comment by yovca** [comment]
Yes, thank you!
I think that is the problem with v2....

**Comment by dwainscheeren** [comment]
Remove dwains_dashboard in custom_components completely. Then reboot HA and install v3 :) Also don't forget to rename dwains-dashboard in your main ha config folder to dwains-dashboard-v2

**Comment by yovca** [comment]
Thank's friend
I'm working on it, I'll let you know... :)

**Comment by yovca** [comment]
Yeeesssss, that is it!

Problem with old V2 installation, I remove it and install again V3, and everything working

Thank's Dwain!
cheers

**Comment by yovca** [comment]
Solved!

Dwain write...
"Please read all the steps, remove 2.0 completely then reboot, then install 3.0  - https://dwainscheeren.github.io/dwains-lovelace-dashboard/v3/information/migrate-v2-to-v3.html"
 
Thank's Dwain
