### ISSUE TITLE
HA 2022.7.0b0 breaks editing of Dwains Dashboard

### ISSUE THREAD

**Issue by thewazz1** [dwainscheeren/dwains-lovelace-dashboard#581]
I upgraded to HA 2022.7.0b0 and have noticed that whenever I try editing anything on any of my area pages that it is not working.  Originally saw the issue when trying to disable an entity in DD and it would not remove from the edit screen.  I would then refresh and my main DD dashboard would no longer come up, or the entities page, but some of the more_pages would still come up.  Looked into this further and it turns out that /config/dwains-dashboard/configs/entities.yaml is changing to 0 bytes when trying to edit anything.  I have confirmed that this happens when disabling, hiding, excluding entities, as well as when trying to change entity settings (such as number of columns).  So far have only been able to recover my dashboard by copying entities.yaml from a backup file that I have.  I am seeing the following error in my logs:

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/dwains_dashboard/__init__.py:986 
Integration: Home Assistant WebSocket API (documentation, issues) 
First occurred: 10:38:57 AM (7 occurrences) 
Last logged: 11:05:10 AM

[140380959735184] Error handling message: Unknown error (unknown_error)
[140380960076416] Error handling message: Unknown error (unknown_error)
[140380900743904] Error handling message: Unknown error (unknown_error)
[140380958454784] Error handling message: Unknown error (unknown_error)
[140380895776720] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/dwains_dashboard/__init__.py", line 986, in ws_handle_edit_entity_bool_value
    yaml.safe_dump(entities, f, default_flow_style=False)
  File "/usr/local/lib/python3.10/site-packages/yaml/__init__.py", line 269, in safe_dump
    return dump_all([data], stream, Dumper=SafeDumper, **kwds)
  File "/usr/local/lib/python3.10/site-packages/yaml/__init__.py", line 241, in dump_all
    dumper.represent(data)
  File "/usr/local/lib/python3.10/site-packages/yaml/representer.py", line 27, in represent
    node = self.represent_data(data)
  File "/usr/local/lib/python3.10/site-packages/yaml/representer.py", line 48, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/usr/local/lib/python3.10/site-packages/yaml/representer.py", line 207, in represent_dict
    return self.represent_mapping('tag:yaml.org,2002:map', data)
  File "/usr/local/lib/python3.10/site-packages/yaml/representer.py", line 118, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/usr/local/lib/python3.10/site-packages/yaml/representer.py", line 58, in represent_data
    node = self.yaml_representers[None](self, data)
  File "/usr/local/lib/python3.10/site-packages/yaml/representer.py", line 231, in represent_undefined
    raise RepresenterError("cannot represent an object", data)
yaml.representer.RepresenterError: ('cannot represent an object', OrderedDict([('disabled', True)]))

**Comment by FrancoLoco** [comment]
i have the same issue

**Comment by thewazz1** [comment]
I have confirmed that this issue is still in the HA release 2022.7.0

**Comment by davros123** [comment]
Thankyou @thewazz1 - This is an workaround allowed me to continue using the dash while awaiting the fix.

**Comment by dwainscheeren** [comment]
See #588
