### ISSUE TITLE
Error setting up entry for dwains_dashboard

### ISSUE THREAD

**Issue by ZacheryGlass** [dwainscheeren/dwains-lovelace-dashboard#606]
Initial attempt to install via HACS led to the following error message.

> Logger: homeassistant.config_entries
> Source: custom_components/dwains_dashboard/process_yaml.py:126
> Integration: Dwains Dashboard ([documentation](https://dwainscheeren.github.io/dwains-lovelace-dashboard/), [issues](https://github.com/dwainscheeren/dwains-lovelace-dashboard/issues))
> First occurred: 11:44:32 AM (1 occurrences)
> Last logged: 11:44:32 AM
> Error setting up entry for dwains_dashboard

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 353, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/dwains_dashboard/__init__.py", line 1579, in async_setup_entry
    process_yaml(hass, config_entry)
  File "/config/custom_components/dwains_dashboard/process_yaml.py", line 126, in process_yaml
    if "name" in filecontent and "icon" in filecontent:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by Graham350z** [comment]
I have exactly the same issue.
does anyone have a solution?

**Comment by behold81** [comment]
I have the same issue trying to set this up for the first time.

**Comment by dwainscheeren** [comment]
Do you both got a dwains-dashboard config folder from a previous installation or tried installing a more page?

**Comment by behold81** [comment]
I can't get that far. This is a brand new install. so there is no old config folder or more page to access. this is failing to initialize in integrations in the first place.

**Comment by dwainscheeren** [comment]
Line 126 is only fired/executed when there is a folder dwains-dashboard/configs/more_pages so that is very strange that you get an error on line 126. 😕

**Comment by behold81** [comment]
Worked out the issue. Turns out where I have tried using it in the past the high level dwains-dashboard/configs/ was causing issues. removing this fully and restarting has now got this working. 

Hopefully the same issue for Graham and Zachary

**Comment by Graham350z** [comment]
I managed to get mine working by restoring a previous backup from about a month prior.

⁣Get TypeApp for Android ​

On 4 Aug 2022, 13:22, at 13:22, Dwain Scheeren ***@***.***> wrote:
>Line 126 is only fired/executed when there is a folder
>dwains-dashboard/configs/more_pages so that is very strange that you
>get an error on line 126. 😕 
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/dwainscheeren/dwains-lovelace-dashboard/issues/606#issuecomment-1205181717
>You are receiving this because you commented.
>
>Message ID:
***@***.***>

**Comment by tiberius25** [comment]
Same problem a long time, since Home Assistant 2022.7

**Comment by dwainscheeren** [comment]
Thanks for reporting this.

Dwains Dashboard 3.9.0 has now been released, and the source files for DD3 are available in this repository.

DD3 is no longer under active feature development and will slowly be phased out. Active development continues in Dwains Dashboard Next:
https://github.com/dwainscheeren/dwains-dashboard-next

At the time of writing, Dwains Dashboard Next is still in alpha.

If this issue is a feature request, please check whether it fits Dwains Dashboard Next instead.

If this issue is a bug, please retest with DD3 version 3.9.0. If the bug is still reproducible there, please open a new issue with:

- Home Assistant version
- Dwains Dashboard version
- browser and device
- browser console errors
- clear reproduction steps

For more context, see #906.

For that reason, this older issue is being closed as part of the DD3 issue tracker cleanup.
