### ISSUE TITLE
Connecting through HA app and Nabu Casa 

### ISSUE THREAD

**Issue by designasaw** [dwainscheeren/dwains-lovelace-dashboard#673]
Hi, 
First off, love this dashboard. Couldn't have got to this good a look and functionality on my own so, thank you.

Issue i'm having is if i use my app (android) and connect using my Nabu casa url rather than connecting local to my home assistant IP. I get an error 
" Custom element doesn't exist: dwains-dashboard-layout.

title: Home
icon: mdi: home
path: home
type: custom:dwains-dashboard-layout
cards:
 - type: custom:homepage-card"

Where have i gone wrong? Works fine if i go back to connect to the IP but that doesn't give me access outside the house. I like using the Nabu casa method to support the project, so i'd like to stick to that. 
I'm guessing i've got a bit of config wrong at some point but i'm lost as to where.

Thank you.

**Comment by designasaw** [comment]
I'm also getting this error in the logs
"Logger: homeassistant.config_entries
Source: components/frontend/__init__.py:281
First occurred: 15:32:10 (1 occurrences)
Last logged: 15:32:10

Error setting up entry for dwains_dashboard
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 382, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/dwains_dashboard/__init__.py", line 1581, in async_setup_entry
    load_dashboard(hass, config_entry)
  File "/config/custom_components/dwains_dashboard/load_dashboard.py", line 36, in load_dashboard
    _register_panel(hass, dashboard_url, "yaml", dashboard_config, False)
  File "/usr/src/homeassistant/homeassistant/components/lovelace/__init__.py", line 246, in _register_panel
    frontend.async_register_built_in_panel(hass, DOMAIN, **kwargs)
  File "/usr/src/homeassistant/homeassistant/components/frontend/__init__.py", line 281, in async_register_built_in_panel
    raise ValueError(f"Overwriting panel {panel.frontend_url_path}")
ValueError: Overwriting panel dwains-dashboard"

**Comment by designasaw** [comment]
Ignore me. Read the install guide again and found the solution. Sorry.
