### ISSUE TITLE
Installing Blueprint didn`t worg

### ISSUE THREAD

**Issue by HenkCenk** [dwainscheeren/dwains-lovelace-dashboard#778]
Today i tried to install a new page in Dwains Dashbord. Followed the Installation an got this protokoll:

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:133
First occurred: 16:38:49 (3 occurrences)
Last logged: 16:38:50

Detected that custom integration 'dwains_dashboard' uses deprecated 'SafeLineLoader' instead of 'PythonSafeLoader', which will stop working in HA Core 2024.6, at custom_components/dwains_dashboard/process_yaml.py, line 69: loader.SafeLineLoader.add_constructor("!include", _include_yaml), please create a bug report at https://github.com/dwainscheeren/dwains-lovelace-dashboard/issues
Detected that custom integration 'dwains_dashboard' uses deprecated 'SafeLineLoader' instead of 'PythonSafeLoader', which will stop working in HA Core 2024.6, at custom_components/dwains_dashboard/process_yaml.py, line 46: return loader.yaml.load(config_file, Loader=lambda stream: loader.SafeLineLoader(stream, secrets)) or OrderedDict(), please report it to the author of the 'dwains_dashboard' custom integration
Detected that custom integration 'dwains_dashboard' uses deprecated 'SafeLineLoader' instead of 'PythonSafeLoader', which will stop working in HA Core 2024.6, at custom_components/dwains_dashboard/process_yaml.py, line 43: return loader.yaml.load(stream, Loader=lambda _stream: loader.SafeLineLoader(_stream, secrets)) or OrderedDict(), please report it to the author of the 'dwains_dashboard' custom integration

and this:

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/dwains_dashboard/__init__.py:252
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 16:39:30 (1 occurrences)
Last logged: 16:39:30

[547822131520] Error handling message: Unknown error (unknown_error) Henk from 5.147.169.154 (Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/dwains_dashboard/__init__.py", line 252, in ws_handle_install_blueprint
    filecontent = yaml.safe_load(json.loads(msg["yamlCode"]))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yaml/__init__.py", line 79, in load
    loader = Loader(stream)
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yaml/loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "/usr/local/lib/python3.11/site-packages/yaml/reader.py", line 85, in __init__
    self.determine_encoding()
  File "/usr/local/lib/python3.11/site-packages/yaml/reader.py", line 124, in determine_encoding
    self.update_raw()
  File "/usr/local/lib/python3.11/site-packages/yaml/reader.py", line 178, in update_raw
    data = self.stream.read(size)
           ^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'read'

Is there anything, i can doe?

**Comment by dwainscheeren** [comment]
This will be fixed in version 3.7 😄 

Please consider a donation for my work.
https://www.buymeacoffee.com/FAkYvrx
or
https://www.paypal.me/dwainscheeren
or 
https://github.com/sponsors/dwainscheeren
Thank you in advance ❤️
