### ISSUE TITLE
Uncaught error from Chrome

### ISSUE THREAD

**Issue by de-Techneut** [dwainscheeren/dwains-lovelace-dashboard#820]
Dwains Dashboard 3.7.1
Core 2024.7.0

Getting the following Error:
```
Logger: frontend.js.latest.202407030
Source: components/system_log/__init__.py:333
First occurred: 14:53:32 (1 occurrences)
Last logged: 14:53:32

Uncaught error from Chrome 126.0.0.0 on Windows 10 TypeError: Illegal constructor (custom element class must be registered with global customElements registry to be newable) new window.HTMLElement (src/scoped-custom-element-registry.js:168:12) e=window,r=e.trustedTypes,h=r?r.emptyScript:"",o=e.reactiveElementPolyfillSupport,n={toAttribute(t,i){switch (//dwains-dashboard/node_modules/@lit/reactive-element/reactive-element.js:6:552) t{constructor(){super (//dwains-dashboard/node_modules/lit/node_modules/lit-element/lit-element.js:6:53) constructor (//dwains-dashboard/src/dwains-navigation-card.js:109:8) (!root.shadowRoot.querySelector (//dwains-dashboard/src/dwains-dashboard.js:152:59) buildDwainsNavigation (//dwains-dashboard/src/dwains-dashboard.js:116:19) path.substring (//dwains-dashboard/src/dwains-dashboard.js:48:17) dispatchEvent (src/common/dom/fire_event.ts:76:7) mainWindow.history.replaceState (src/common/navigate.ts:44:12) this.route!.prefix}/${path}?${addSearchParam (src/panels/lovelace/hui-root.ts:826:15)
```

When this happens I see this on the Dwains Dashboard homepage.

![image](https://github.com/dwainscheeren/dwains-lovelace-dashboard/assets/60130444/f49f118d-c5ab-4750-ac5c-01df7e1b21c6)

Also getting the same error when using the HomeAssitant app on my phone.  On my chrome browser clearing Cache solves the issue and on my phone I need to clear the app out of my recent apps.

**Comment by djiwhy** [comment]
Same error here.
Blank page on Firefox with :

```
Uncaught (in promise) 
Object { code: "unknown_error", message: "Unknown error" }
​
code: "unknown_error"
​message: "Unknown error"
```

Loaded in chrome : 

```
dwains-dashboard.js:35 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'connection')
    at new l (dwains-dashboard.js:35:9)
    at dwains-dashboard.js:164:35
l @ dwains-dashboard.js:35
(anonymous) @ dwains-dashboard.js:164
Promise.then (async)
919 @ dwains-dashboard.js:162
i @ bootstrap:19
(anonymous) @ startup:4
(anonymous) @ startup:27
```
In Ha Logs :

```
Enregistreur: homeassistant.helpers.frame
Source: helpers/frame.py:151
S'est produit pour la première fois: 22 juillet 2024 à 21:59:38 (2 occurrences)
Dernier enregistrement: 22 juillet 2024 à 21:59:42

Detected code that calls async_forward_entry_setup for integration, dwains_dashboard with title: Admin Dashboard and entry_id: 7af0d28fa65389da04d884df442ab600, which is deprecated and will stop working in Home Assistant 2025.6, await async_forward_entry_setups instead. Please report this issue.
Detected code that calls async_forward_entry_setup for integration browser_mod with title: Browser Mod and entry_id: 87549770ce9eb8caab86b6f642b6fa22, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.
```

And :

```
Enregistreur: frontend.js.latest.202407050
Source: components/system_log/__init__.py:333
S'est produit pour la première fois: 20:14:30 (1 occurrences)
Dernier enregistrement: 20:14:30

Uncaught error from Firefox 115.0 on Windows 10 TypeError: e is null applyDwainsTheme (//dwains-dashboard/src/dwains-dashboard.js:105:8) path.substring (//dwains-dashboard/src/dwains-dashboard.js:47:17)
```

With the Companion app, same thing, blank page. Even if I kill the app or delete the cache and data.

My HA version :

```
Core 2024.7.1
Supervisor 2024.06.2
Operating System 12.4
User Interface 20240705.0
```

**Comment by dwainscheeren** [comment]
Thanks for reporting this.

Dwains Dashboard 3.9.0 has now been released, and the source files for DD3 are available in this repository.

DD3 is no longer under active feature development and will slowly be phased out. Active development continues in Dwains Dashboard Next:
https://github.com/dwainscheeren/dwains-dashboard-next

At the time of writing, Dwains Dashboard Next is still in alpha.

If this issue is a feature request, please check whether it fits Dwains Dashboard Next instead.

If this issue is a bug, please retest with DD3 version 3.9.0. If the bug is still reproducible there, please open a new issue with:

- Home Assistant version
- Dwains Dashboard version
- browser and device
- browser console errors
- clear reproduction steps

For more context, see #906.

For that reason, this older issue is being closed as part of the DD3 issue tracker cleanup.
