### ISSUE TITLE
Unable to Create Blueprints

### ISSUE THREAD

**Issue by tropicthedev** [dwainscheeren/dwains-lovelace-dashboard#822]
Hi, I just installed the dashboard and I am loving it but there is an issue when trying to use blueprints. When I paste the yaml config and press the installation button nothing happens and there is actually an error that occurs in the home assistant logs

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/dwains_dashboard/__init__.py", line 252, in ws_handle_install_blueprint
    filecontent = yaml.safe_load(json.loads(msg["yamlCode"]))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/yaml/__init__.py", line 79, in load
    loader = Loader(stream)
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/yaml/loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "/usr/local/lib/python3.12/site-packages/yaml/reader.py", line 85, in __init__
    self.determine_encoding()
  File "/usr/local/lib/python3.12/site-packages/yaml/reader.py", line 124, in determine_encoding
    self.update_raw()
  File "/usr/local/lib/python3.12/site-packages/yaml/reader.py", line 178, in update_raw
    data = self.stream.read(size)
           ^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'read'

Love the dashboard otherwise and keep up the good work

**Comment by roroid** [comment]
same here

**Comment by mokerhamer** [comment]
Same here, first time user using latest version 3.7.1.

![image](https://github.com/user-attachments/assets/e3b2212d-e891-423c-ba21-a66ffbfad2e3)
![image](https://github.com/user-attachments/assets/806ced6e-d9f9-47d3-b355-4eb002f66c1f)

**Comment by mokerhamer** [comment]
Got it working:

Changed  in custom_components/dwains_dashboard/__init__.py Line 251 and 252

From:
    #filecontent = json.loads(msg["yamlCode"])
    filecontent = yaml.safe_load(json.loads(msg["yamlCode"]))

To:
    filecontents = json.loads(msg["yamlCode"])
    filecontent = yaml.safe_load(json.dumps(filecontents))

**Comment by Bosty01** [comment]
Ah no joy for me. Still not working.

**Comment by Bosty01** [comment]
> Got it working:
> 
> Changed in custom_components/dwains_dashboard/**init**.py Line 251 and 252
> 
> From: #filecontent = json.loads(msg["yamlCode"]) filecontent = yaml.safe_load(json.loads(msg["yamlCode"]))
> 
> To: filecontents = json.loads(msg["yamlCode"]) filecontent = yaml.safe_load(json.dumps(filecontents))

No joy for me. Still not installing.

**Comment by mokerhamer** [comment]
> > Got it working:
> > Changed in custom_components/dwains_dashboard/**init**.py Line 251 and 252
> > From: #filecontent = json.loads(msg["yamlCode"]) filecontent = yaml.safe_load(json.loads(msg["yamlCode"]))
> > To: filecontents = json.loads(msg["yamlCode"]) filecontent = yaml.safe_load(json.dumps(filecontents))
> 
> No joy for me. Still not installing.

dit you restart home assistant?
![image](https://github.com/user-attachments/assets/822b9d2c-f20f-4b53-9215-e8c402fb78ff)

**Comment by Bosty01** [comment]
> > > Got it working:
> > > Changed in custom_components/dwains_dashboard/**init**.py Line 251 and 252
> > > From: #filecontent = json.loads(msg["yamlCode"]) filecontent = yaml.safe_load(json.loads(msg["yamlCode"]))
> > > To: filecontents = json.loads(msg["yamlCode"]) filecontent = yaml.safe_load(json.dumps(filecontents))
> > 
> > 
> > No joy for me. Still not installing.
> 
> dit you restart home assistant? !

That was it. 99% of my issues would go away if I remembered to restart after making changes. Thanks for finding this.

**Comment by mokerhamer** [comment]
> > > > Got it working:
> > > > Changed in custom_components/dwains_dashboard/**init**.py Line 251 and 252
> > > > From: #filecontent = json.loads(msg["yamlCode"]) filecontent = yaml.safe_load(json.loads(msg["yamlCode"]))
> > > > To: filecontents = json.loads(msg["yamlCode"]) filecontent = yaml.safe_load(json.dumps(filecontents))
> > > 
> > > 
> > > No joy for me. Still not installing.
> > 
> > 
> > dit you restart home assistant? !
> 
> That was it. 99% of my issues would go away if I remembered to restart after making changes. Thanks for finding this.

cheers buddy, glad to help

**Comment by mokerhamer** [comment]
> same here

check solution few posts up.

**Comment by Stephonomon** [comment]
Not working for me. Am I the only one? Version 3.7.1, restarted several times.

<img width="701" alt="image" src="https://github.com/user-attachments/assets/f506c676-f1cb-4997-a308-582906912e44">

**Comment by Stephonomon** [comment]
Works.

**Comment by owens-ben** [comment]
BOOM 

> Got it working:
> 
> Changed in custom_components/dwains_dashboard/**init**.py Line 251 and 252
> 
> From: #filecontent = json.loads(msg["yamlCode"]) filecontent = yaml.safe_load(json.loads(msg["yamlCode"]))
> 
> To: filecontents = json.loads(msg["yamlCode"]) filecontent = yaml.safe_load(json.dumps(filecontents))

This works! Gotta restart HA too.

**Comment by spike631** [comment]
nogo on HA v 2024.10.4, restarted HA, cleared cache. Any other suggestions?

**Comment by ben19840425** [comment]
same here. blueprint can be installed. new page is not working. always pointing to the home page.

**Comment by somehuman60** [comment]
> nogo on HA v 2024.10.4, restarted HA, cleared cache. Any other suggestions?

same here. update: used fix here:

(https://github.com/dwainscheeren/dwains-lovelace-dashboard/pull/833)

now can install blueprint, but click on it lead to the homepage

**Comment by jorenchr** [comment]
> > nogo on HA v 2024.10.4, restarted HA, cleared cache. Any other suggestions?
> 
> same here. update: used fix here:
> 
> (#833)
> 
> now can install blueprint, but click on it lead to the homepage

Idem. Blueprint installations work but always going to homepage when blueprint page is created.
Any solutions by now?

**Comment by dwainscheeren** [comment]
Reboot HA after creating the more page.

**Comment by wtf97996** [comment]
> filecontent = yaml.safe_load(json.dumps(filecontents))

Great job!

thx

**Comment by wtf97996** [comment]
> Got it working:
> 
> Changed in custom_components/dwains_dashboard/**init**.py Line 251 and 252
> 
> From: #filecontent = json.loads(msg["yamlCode"]) filecontent = yaml.safe_load(json.loads(msg["yamlCode"]))
> 
> To: filecontents = json.loads(msg["yamlCode"]) filecontent = yaml.safe_load(json.dumps(filecontents))

Great Job!

thx!

**Comment by jordanwmcdonald** [comment]
> Got it working:
> 
> Changed in custom_components/dwains_dashboard/**init**.py Line 251 and 252
> 
> From: #filecontent = json.loads(msg["yamlCode"]) filecontent = yaml.safe_load(json.loads(msg["yamlCode"]))
> 
> To: filecontents = json.loads(msg["yamlCode"]) filecontent = yaml.safe_load(json.dumps(filecontents))

Thank you so very much!

**Comment by dwainscheeren** [comment]
Thanks for reporting this.

Dwains Dashboard 3.9.0 has now been released, and the source files for DD3 are available in this repository.

DD3 is no longer under active feature development and will slowly be phased out. Active development continues in Dwains Dashboard Next:
https://github.com/dwainscheeren/dwains-dashboard-next

At the time of writing, Dwains Dashboard Next is still in alpha.

If this issue is a feature request, please check whether it fits Dwains Dashboard Next instead.

If this issue is a bug, please retest with DD3 version 3.9.0. If the bug is still reproducible there, please open a new issue with:

- Home Assistant version
- Dwains Dashboard version
- browser and device
- browser console errors
- clear reproduction steps

For more context, see #906.

For that reason, this older issue is being closed as part of the DD3 issue tracker cleanup.
