### ISSUE TITLE
ERROR 

### ISSUE THREAD

**Issue by HomeAssist87** [dwainscheeren/dwains-lovelace-dashboard#847]
Detected code that calls async_forward_entry_setup (deprecated)
for integration, dwains_dashboard ... This will stop working in Home Assistant 2025.6

Likely Cause
The Dwains Dashboard custom integration uses a soon-to-be-deprecated function.
Suggested Fixes
Update Dwains Dashboard: Make sure you have the newest version that addresses this.
Report: If no update is available, open an issue on Dwains Dashboard’s GitHub so they can implement async_forward_entry_setups.

Detected custom integration dwains_dashboard calls hass.http.register_static_path
deprecated because it does blocking I/O in the event loop...

Likely Cause
Similar to the above, Dwains Dashboard is using an older approach for registering static paths.
Suggested Fixes
Update: Again, check for the newest Dwains Dashboard release.
Report: If not fixed, report to the developer. They need to switch to async_register_static_paths.

Deprecated calls in Dwains Dashboard
a) async_forward_entry_setup → async_forward_entry_setups
b) hass.http.register_static_path (blocking I/O)
(Warning) helpers/frame.py

Likely Cause

Dwains Dashboard integration code is using older methods that will eventually be removed in future Home Assistant versions.

**Comment by nohat** [comment]
I got these related errors since 2025.1:

```
2025-01-08 19:08:42.049 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open with args ('/config/dwains-dashboard/configs/settings.yaml',) inside the event loop by custom integration 'dwains_dashboard' at custom_components/dwains_dashboard/__init__.py, line 118: with open(hass.config.path("dwains-dashboard/configs/settings.yaml")) as f: (offender: /config/custom_components/dwains_dashboard/__init__.py, line 118: with open(hass.config.path("dwains-dashboard/configs/settings.yaml")) as f:), please create a bug report at https://github.com/dwainscheeren/dwains-lovelace-dashboard/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 227, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 213, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 154, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 707, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 678, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 2025, in _run_once
    handle._run()
  File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py", line 480, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_app.py", line 569, in _handle
    return await handler(request)
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 210, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 86, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/http.py", line 57, in get
    return await WebSocketHandler(request.app[KEY_HASS], request).async_handle()
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/http.py", line 343, in async_handle
    await self._async_websocket_command_phase(connection)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/http.py", line 494, in _async_websocket_command_phase
    async_handle_str(command_msg_data)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/connection.py", line 235, in async_handle
    handler(self.hass, self, msg)
  File "/config/custom_components/dwains_dashboard/__init__.py", line 118, in websocket_get_configuration
    with open(hass.config.path("dwains-dashboard/configs/settings.yaml")) as f:
```

The error log indicates that a **blocking I/O operation** (`open`) was detected inside the event loop in the `dwains_dashboard` custom integration. This violates the non-blocking nature of the Home Assistant event loop and can lead to degraded performance or even application freezes.

1. **Blocking Call Detected**:
   - The `open` function is used synchronously to read YAML files located in `/config/dwains-dashboard/`.
   - Home Assistant's event loop is asynchronous and should not have blocking operations like file reads. Instead, it expects asynchronous file handling.

2. **Location of the Offending Code**: [custom_components/dwains_dashboard/\_\_init\_\_.py:118](https://github.com/dwainscheeren/dwains-lovelace-dashboard/blob/3.0/custom_components/dwains_dashboard/__init__.py#L93-L207)

3. **Recommendation from developer documentation about [Blocking operations with asyncio](https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open)**:
   - The warning suggests switching to non-blocking asynchronous file operations. Developers should replace the blocking `open` call with an asynchronous equivalent using `aiofiles`.

**Comment by dwainscheeren** [comment]
Thanks for reporting this.

Dwains Dashboard 3.9.0 has now been released, and the source files for DD3 are available in this repository.

DD3 is no longer under active feature development and will slowly be phased out. Active development continues in Dwains Dashboard Next:
https://github.com/dwainscheeren/dwains-dashboard-next

At the time of writing, Dwains Dashboard Next is still in alpha.

If this issue is a feature request, please check whether it fits Dwains Dashboard Next instead.

If this issue is a bug, please retest with DD3 version 3.9.0. If the bug is still reproducible there, please open a new issue with:

- Home Assistant version
- Dwains Dashboard version
- browser and device
- browser console errors
- clear reproduction steps

For more context, see #906.

For that reason, this older issue is being closed as part of the DD3 issue tracker cleanup.
